export function getBootstrap() {
    return window.__GHOSN_ADMIN__ ?? {};
}

export const CONTENT = {
    en: {
        role: 'Administrator',
        panel: 'Admin Panel',
        welcome: (name) => `Welcome back, ${name}`,
        search: 'Search…',
        notifications: 'Notifications',
        viewSite: 'View website',
        logout: 'Log out',
        chart: { title: 'Donations overview', sub: 'Last 7 months' },
        progress: { title: 'Campaign progress' },
        recentDonations: 'Recent donations',
        recentVolunteers: 'Recent applications',
        viewAll: 'View all',
        quickLinks: 'Quick links',
        homepageBuilder: 'Homepage',
        nextSteps: 'Next steps',
        nextStepsBody: 'Edit homepage sections in Pages Builder. Saved changes appear on the public homepage immediately.',
        emptyDonations: 'No donations yet.',
        emptyVolunteers: 'No applications yet.',
        emptyCampaigns: 'No campaigns to show.',
        dashboardTitle: 'Dashboard',
        openMenu: 'Open menu',
        closeMenu: 'Close menu',
        adminNav: 'Admin navigation',
        status: {
            paid: 'Paid',
            pending: 'Pending',
            approved: 'Approved',
            rejected: 'Rejected',
            failed: 'Failed',
            cancelled: 'Cancelled',
            refunded: 'Refunded',
        },
        kpiIcons: {
            raised: 'donation',
            campaigns: 'campaign',
            pages: 'pages',
            sections: 'sections',
        },
    },
    ar: {
        role: 'مدير',
        panel: 'لوحة الإدارة',
        welcome: (name) => `أهلًا بعودتك، ${name}`,
        search: 'بحث…',
        notifications: 'الإشعارات',
        viewSite: 'عرض الموقع',
        logout: 'تسجيل الخروج',
        chart: { title: 'نظرة عامة على التبرّعات', sub: 'آخر ٧ أشهر' },
        progress: { title: 'تقدّم الحملات' },
        recentDonations: 'أحدث التبرّعات',
        recentVolunteers: 'أحدث الطلبات',
        viewAll: 'عرض الكل',
        quickLinks: 'روابط سريعة',
        homepageBuilder: 'الصفحة الرئيسية',
        nextSteps: 'الخطوات التالية',
        nextStepsBody: 'حرّر أقسام الصفحة الرئيسية من منشئ الصفحات. التغييرات المحفوظة تظهر على الموقع فوراً.',
        emptyDonations: 'لا توجد تبرّعات بعد.',
        emptyVolunteers: 'لا توجد طلبات بعد.',
        emptyCampaigns: 'لا توجد حملات للعرض.',
        dashboardTitle: 'لوحة التحكم',
        openMenu: 'فتح القائمة',
        closeMenu: 'إغلاق القائمة',
        adminNav: 'تنقل لوحة التحكم',
        status: {
            paid: 'مدفوع',
            pending: 'قيد المراجعة',
            approved: 'مقبول',
            rejected: 'مرفوض',
            failed: 'فشل',
            cancelled: 'ملغى',
            refunded: 'مسترد',
        },
        kpiIcons: {
            raised: 'donation',
            campaigns: 'campaign',
            pages: 'pages',
            sections: 'sections',
        },
    },
};
