<?php

/**
 * About Us page defaults — matches GHOSN Relief Team Landing Page / About Us.dc.html
 */
return [
    'sections' => [
        'hero' => true,
        'intro' => true,
        'stats' => true,
        'pillars' => true,
        'values' => true,
        'story' => true,
        'team' => true,
        'partners' => true,
        'cta' => true,
    ],
    'hero' => [
        'eyebrow_en' => 'About GHOSN',
        'eyebrow_ar' => 'من نحن',
        'title_en' => 'Giving that grows. Impact that lasts.',
        'title_ar' => 'عطاءٌ ينمو... وأثرٌ يبقى',
        'subtitle_en' => 'We are a humanitarian relief team turning everyday generosity into lasting, dignified change for families and communities.',
        'subtitle_ar' => 'نحن فريق إغاثة إنساني يحوّل العطاء اليومي إلى تغييرٍ دائمٍ يحفظ كرامة الأسر والمجتمعات.',
        'image_url' => '',
        'image_media_id' => null,
    ],
    'intro' => [
        'eyebrow_en' => 'Who We Are',
        'eyebrow_ar' => 'من نحن',
        'title_en' => 'Relief rooted in dignity and hope',
        'title_ar' => 'إغاثةٌ تتجذّر في الكرامة والأمل',
        'paragraphs_en' => [
            'GHOSN — meaning "branch" — grew from a simple belief: generosity, given with care, takes root and keeps growing long after the moment of giving.',
            'We work hand in hand with local communities to deliver relief that is timely, transparent, and always respectful of human dignity.',
            'From clean water to food security, education and shelter, every program is designed to empower families to stand on their own.',
        ],
        'paragraphs_ar' => [
            'غُصن — ومعناه الفرع — نشأ من إيمانٍ بسيط: أنّ العطاء حين يُقدَّم بعناية يتجذّر ويستمرّ في النمو بعد لحظة العطاء بزمنٍ طويل.',
            'نعمل يدًا بيد مع المجتمعات المحلية لتقديم إغاثةٍ سريعةٍ وشفّافة، تحفظ كرامة الإنسان دائمًا.',
            'من المياه النظيفة إلى الأمن الغذائي والتعليم والمأوى، كل برنامج مصمَّم لتمكين الأسر من الاعتماد على نفسها.',
        ],
        'image_url' => '',
        'image_media_id' => null,
        'video_url' => '',
        'video_cover_url' => '',
        'video_cover_media_id' => null,
    ],
    'stats' => [
        ['end' => 128000, 'suffix' => '+', 'label_en' => 'Beneficiaries reached', 'label_ar' => 'المستفيدون'],
        ['end' => 1450, 'suffix' => '+', 'label_en' => 'Volunteers', 'label_ar' => 'المتطوعون'],
        ['end' => 60, 'suffix' => '+', 'label_en' => 'Communities served', 'label_ar' => 'مجتمعًا خدمناه'],
        ['end' => 8, 'suffix' => '', 'label_en' => 'Years of impact', 'label_ar' => 'سنوات من الأثر'],
    ],
    'pillars' => [
        [
            'key' => 'mission',
            'title_en' => 'Our Mission',
            'title_ar' => 'رسالتنا',
            'body_en' => 'To deliver dignified, transparent humanitarian relief that meets urgent needs while building the foundations for lasting self-reliance.',
            'body_ar' => 'تقديم إغاثة إنسانية كريمة وشفّافة تلبّي الاحتياجات العاجلة وتبني أسس الاعتماد الدائم على الذات.',
        ],
        [
            'key' => 'vision',
            'title_en' => 'Our Vision',
            'title_ar' => 'رؤيتنا',
            'body_en' => 'A world where every act of giving becomes lasting hope — where communities grow strong, healthy, and independent.',
            'body_ar' => 'عالمٌ يتحوّل فيه كل عطاءٍ إلى أملٍ دائم — حيث تنمو المجتمعات قويةً وصحيةً ومستقلة.',
        ],
        [
            'key' => 'values',
            'title_en' => 'Our Approach',
            'title_ar' => 'منهجنا',
            'body_en' => 'Community-led, sustainable programs run with local partners, measured by real impact and answerable to every donor.',
            'body_ar' => 'برامج مستدامة يقودها المجتمع وتُنفَّذ مع شركاء محليّين، تُقاس بالأثر الحقيقي وتُساءل أمام كل متبرّع.',
        ],
    ],
    'values' => [
        'title_en' => 'What We Stand For',
        'title_ar' => 'قيمنا',
        'intro_en' => 'The values that guide every decision, every campaign, and every hand we extend.',
        'intro_ar' => 'القيم التي توجّه كل قرارٍ وكل حملةٍ وكل يدٍ نمدّها.',
        'items' => [
            ['key' => 'heart', 'title_en' => 'Compassion', 'title_ar' => 'الرحمة', 'body_en' => 'We meet people with warmth and respect, never pity.', 'body_ar' => 'نلتقي الناس بالدفء والاحترام، لا بالشفقة.'],
            ['key' => 'shield', 'title_en' => 'Integrity', 'title_ar' => 'النزاهة', 'body_en' => 'Full transparency — every donation is tracked and accountable.', 'body_ar' => 'شفافية كاملة — كل تبرّع يُتتبّع ويخضع للمساءلة.'],
            ['key' => 'sprout', 'title_en' => 'Sustainability', 'title_ar' => 'الاستدامة', 'body_en' => 'We build programs that keep giving for years, not moments.', 'body_ar' => 'نبني برامج تمنح لسنوات، لا للحظات.'],
            ['key' => 'hands', 'title_en' => 'Community', 'title_ar' => 'المجتمع', 'body_en' => 'Local voices lead; we walk alongside, not ahead.', 'body_ar' => 'الأصوات المحلية تقود، ونحن نسير إلى جانبها لا أمامها.'],
        ],
    ],
    'story' => [
        'eyebrow_en' => 'Our Journey',
        'eyebrow_ar' => 'مسيرتنا',
        'title_en' => 'How GHOSN grew',
        'title_ar' => 'كيف نما غُصن',
        'milestones' => [
            ['year_en' => '2018', 'year_ar' => '٢٠١٨', 'title_en' => 'A branch takes root', 'title_ar' => 'فرعٌ يتجذّر', 'body_en' => 'GHOSN begins as a small group of volunteers delivering food baskets to families in need.', 'body_ar' => 'بدأ غُصن كمجموعة صغيرة من المتطوعين توصل سلال الغذاء للأسر المحتاجة.'],
            ['year_en' => '2020', 'year_ar' => '٢٠٢٠', 'title_en' => 'Growing outward', 'title_ar' => 'نموٌّ نحو الخارج', 'body_en' => 'We expand into clean water and winter relief, reaching thousands across six regions.', 'body_ar' => 'توسّعنا إلى المياه النظيفة والإغاثة الشتوية، لنصل إلى الآلاف في ست مناطق.'],
            ['year_en' => '2023', 'year_ar' => '٢٠٢٣', 'title_en' => 'Building to last', 'title_ar' => 'بناءٌ يدوم', 'body_en' => 'Sustainable programs launch — solar wells, school meals and vocational training.', 'body_ar' => 'انطلقت برامج مستدامة — آبار شمسية ووجبات مدرسية وتدريب مهني.'],
            ['year_en' => '2026', 'year_ar' => '٢٠٢٦', 'title_en' => 'A lasting canopy', 'title_ar' => 'ظلٌّ وارف', 'body_en' => 'Now 1,450+ volunteers strong, serving 60+ communities with dignity at the center.', 'body_ar' => 'الآن بأكثر من ١٤٥٠ متطوعًا، نخدم أكثر من ٦٠ مجتمعًا والكرامة في القلب.'],
        ],
    ],
    'team' => [
        'eyebrow_en' => 'Our People',
        'eyebrow_ar' => 'فريقنا',
        'title_en' => 'Meet the team',
        'title_ar' => 'تعرّف على الفريق',
        'intro_en' => 'The dedicated people who turn generosity into action every day.',
        'intro_ar' => 'الأشخاص المتفانون الذين يحوّلون العطاء إلى فعلٍ كل يوم.',
        'members' => [
            ['name_en' => 'Yusuf Al-Rashid', 'name_ar' => 'يوسف الرشيد', 'role_en' => 'Founder & Director', 'role_ar' => 'المؤسّس والمدير', 'image_url' => '', 'image_media_id' => null],
            ['name_en' => 'Layla Haddad', 'name_ar' => 'ليلى حدّاد', 'role_en' => 'Programs Lead', 'role_ar' => 'مسؤولة البرامج', 'image_url' => '', 'image_media_id' => null],
            ['name_en' => 'Omar Khalil', 'name_ar' => 'عمر خليل', 'role_en' => 'Field Operations', 'role_ar' => 'العمليات الميدانية', 'image_url' => '', 'image_media_id' => null],
            ['name_en' => 'Sara Mansour', 'name_ar' => 'سارة منصور', 'role_en' => 'Community & Outreach', 'role_ar' => 'المجتمع والتواصل', 'image_url' => '', 'image_media_id' => null],
        ],
    ],
    'partners' => [
        'title_en' => 'Trusted by partners who share our mission',
        'title_ar' => 'يثق بنا شركاء يشاركوننا رسالتنا',
        'items_en' => ['Local Councils', 'Health Alliance', 'Water for All', 'Education Fund', 'Community Trust'],
        'items_ar' => ['المجالس المحلية', 'تحالف الصحة', 'ماء للجميع', 'صندوق التعليم', 'ثقة المجتمع'],
    ],
    'cta' => [
        'title_en' => 'Be part of the giving that grows',
        'title_ar' => 'كن جزءًا من العطاء الذي ينمو',
        'subtitle_en' => 'Support a campaign or join our volunteers — and help turn generosity into lasting impact.',
        'subtitle_ar' => 'ادعم حملةً أو انضم إلى متطوعينا — وساعد في تحويل العطاء إلى أثرٍ دائم.',
        'primary_en' => 'Explore Campaigns',
        'primary_ar' => 'استكشف الحملات',
        'primary_url' => '/campaigns',
        'secondary_en' => 'Join Our Team',
        'secondary_ar' => 'انضم إلى فريقنا',
        'secondary_url' => '/our-team',
    ],
];
