<?php

/**
 * Contact page defaults — matches GHOSN Relief Team Landing Page / Contact.dc.html
 */
return [
    'sections' => [
        'hero' => true,
        'details' => true,
        'form' => true,
        'cta' => true,
    ],
    'form' => [
        'title_en' => 'Send us a message',
        'title_ar' => 'أرسل لنا رسالة',
        'subtitle_en' => 'We usually respond within one business day.',
        'subtitle_ar' => 'نردّ عادةً خلال يوم عملٍ واحد.',
        'name_en' => 'Full name',
        'name_ar' => 'الاسم الكامل',
        'name_ph_en' => 'Your name',
        'name_ph_ar' => 'اسمك',
        'email_en' => 'Email',
        'email_ar' => 'البريد الإلكتروني',
        'email_ph_en' => 'you@email.com',
        'email_ph_ar' => 'you@email.com',
        'subject_en' => 'Subject',
        'subject_ar' => 'الموضوع',
        'subject_ph_en' => 'Choose a topic',
        'subject_ph_ar' => 'اختر موضوعًا',
        'subjects_en' => [
            'General inquiry',
            'Partnership',
            'Volunteering',
            'Media & press',
            'Donation support',
        ],
        'subjects_ar' => [
            'استفسار عام',
            'شراكة',
            'تطوّع',
            'إعلام وصحافة',
            'دعم التبرّعات',
        ],
        'message_en' => 'Message',
        'message_ar' => 'الرسالة',
        'message_ph_en' => 'How can we help you?',
        'message_ph_ar' => 'كيف يمكننا مساعدتك؟',
        'submit_en' => 'Send message',
        'submit_ar' => 'إرسال الرسالة',
        'sending_en' => 'Sending…',
        'sending_ar' => 'جارٍ الإرسال…',
        'success_en' => 'Thank you! Your message has been sent — we will be in touch soon.',
        'success_ar' => 'شكرًا لك! تم إرسال رسالتك — سنتواصل معك قريبًا.',
        'error_en' => 'Something went wrong. Please try again.',
        'error_ar' => 'حدث خطأ ما. حاول مرة أخرى.',
    ],
    'links' => [
        'title_en' => 'Explore the site',
        'title_ar' => 'استكشف الموقع',
        'follow_en' => 'Follow us',
        'follow_ar' => 'تابعنا',
    ],
    'cta' => [
        'title_en' => 'Turn your support into lasting impact',
        'title_ar' => 'حوّل دعمك إلى أثرٍ دائم',
        'subtitle_en' => 'While you are here — a single gift plants hope that keeps growing for families in need.',
        'subtitle_ar' => 'وما دمت هنا — عطاءٌ واحد يزرع أملًا يستمرّ في النمو لأسرٍ محتاجة.',
        'primary_en' => 'Donate Now',
        'primary_ar' => 'تبرّع الآن',
        'secondary_en' => 'Join Our Team',
        'secondary_ar' => 'انضم إلى فريقنا',
        'primary_url' => '/donate',
        'secondary_url' => '/volunteer',
    ],
];
