<?php

return [
    'order' => ['donation', 'privacy', 'terms', 'refund'],

    'slugs' => [
        'donation' => 'donation-policy',
        'privacy' => 'privacy-policy',
        'terms' => 'terms-of-use',
        'refund' => 'refund-policy',
    ],

    'tabs' => [
        'donation' => ['label_en' => 'Donation Policy', 'label_ar' => 'سياسة التبرّع'],
        'privacy' => ['label_en' => 'Privacy Policy', 'label_ar' => 'سياسة الخصوصية'],
        'terms' => ['label_en' => 'Terms of Use', 'label_ar' => 'شروط الاستخدام'],
        'refund' => ['label_en' => 'Refund Policy', 'label_ar' => 'سياسة الاسترداد'],
    ],

    'ui' => [
        'last_updated_en' => 'Last updated',
        'last_updated_ar' => 'آخر تحديث',
        'on_this_page_en' => 'On this page',
        'on_this_page_ar' => 'في هذه الصفحة',
        'contact_note_title_en' => 'Questions about this policy?',
        'contact_note_title_ar' => 'أسئلة حول هذه السياسة؟',
        'contact_note_body_en' => 'Our team is happy to help. Reach us anytime at',
        'contact_note_body_ar' => 'يسعد فريقنا بمساعدتك. تواصل معنا في أي وقت عبر',
        'home_crumb_en' => 'Home',
        'home_crumb_ar' => 'الرئيسية',
    ],

    'pages' => [
        'donation' => [
            'title_en' => 'Donation Policy',
            'title_ar' => 'سياسة التبرّع',
            'subtitle_en' => 'How your generosity is received, protected, and put to work with full transparency.',
            'subtitle_ar' => 'كيف نستقبل عطاءك ونحفظه ونضعه موضع العمل بشفافية كاملة.',
            'updated_en' => 'July 1, 2026',
            'updated_ar' => '١ يوليو ٢٠٢٦',
            'intro_en' => 'This Donation Policy explains how GHOSN Relief Team collects, manages, and allocates the donations entrusted to us. Our commitment is simple: every gift is handled with integrity and directed toward lasting impact.',
            'intro_ar' => 'توضّح سياسة التبرّع هذه كيف يجمع فريق غُصن للإغاثة التبرّعات الموكلة إلينا ويديرها ويوزّعها. التزامنا بسيط: كل عطاءٍ يُدار بنزاهة ويُوجَّه نحو أثرٍ دائم.',
            'sections' => [
                [
                    'heading_en' => 'Use of Donations',
                    'heading_ar' => 'استخدام التبرّعات',
                    'paragraphs_en' => ['Donations are directed to the campaigns and programs for which they are given. Where a gift is unrestricted, GHOSN allocates it to the areas of greatest current need.'],
                    'paragraphs_ar' => ['تُوجَّه التبرّعات إلى الحملات والبرامج التي قُدِّمت لأجلها. وعند عدم التخصيص، يخصّص غُصن التبرّع لمجالات الحاجة الأكثر إلحاحًا.'],
                    'bullets_en' => ['100% of designated gifts reach the chosen cause', 'Operating costs are funded separately from restricted donations', 'Surplus funds are redirected to related active programs'],
                    'bullets_ar' => ['١٠٠٪ من التبرّعات المخصّصة تصل إلى القضية المختارة', 'تُموَّل التكاليف التشغيلية بمعزلٍ عن التبرّعات المقيّدة', 'يُعاد توجيه الفائض إلى برامج نشطة ذات صلة'],
                ],
                [
                    'heading_en' => 'Transparency & Reporting',
                    'heading_ar' => 'الشفافية والتقارير',
                    'paragraphs_en' => ['We publish campaign progress and impact updates so donors can see the results of their giving. Financial summaries are available on request.'],
                    'paragraphs_ar' => ['ننشر تقدّم الحملات وتحديثات الأثر ليرى المتبرّعون نتائج عطائهم. والملخّصات المالية متاحة عند الطلب.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Data & Payment Security',
                    'heading_ar' => 'أمان البيانات والدفع',
                    'paragraphs_en' => ['All payments are processed through secure, industry-standard gateways. GHOSN does not store full card details on its servers.'],
                    'paragraphs_ar' => ['تُعالَج جميع المدفوعات عبر بوّابات آمنة وفق معايير الصناعة. ولا يخزّن غُصن بيانات البطاقات الكاملة على خوادمه.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Receipts',
                    'heading_ar' => 'الإيصالات',
                    'paragraphs_en' => ['A donation receipt is issued for every contribution and, where applicable, is suitable for tax purposes in your region.'],
                    'paragraphs_ar' => ['يُصدَر إيصال تبرّع لكل مساهمة، وهو صالح للأغراض الضريبية في منطقتك حيثما ينطبق.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Contact',
                    'heading_ar' => 'التواصل',
                    'paragraphs_en' => ['For any question about how your donation is used, please contact our team — we welcome your questions and value your trust.'],
                    'paragraphs_ar' => ['لأي سؤالٍ حول كيفية استخدام تبرّعك، يُرجى التواصل مع فريقنا — نرحّب بأسئلتك ونقدّر ثقتك.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
            ],
        ],
        'privacy' => [
            'title_en' => 'Privacy Policy',
            'title_ar' => 'سياسة الخصوصية',
            'subtitle_en' => 'What information we collect, why we collect it, and the choices you have.',
            'subtitle_ar' => 'ما المعلومات التي نجمعها ولماذا، وما الخيارات المتاحة لك.',
            'updated_en' => 'July 1, 2026',
            'updated_ar' => '١ يوليو ٢٠٢٦',
            'intro_en' => 'Your privacy matters to us. This policy describes what personal information GHOSN collects and how we use and protect it.',
            'intro_ar' => 'خصوصيتك تهمّنا. توضّح هذه السياسة ما المعلومات الشخصية التي يجمعها غُصن وكيف نستخدمها ونحميها.',
            'sections' => [
                [
                    'heading_en' => 'Information We Collect',
                    'heading_ar' => 'المعلومات التي نجمعها',
                    'paragraphs_en' => ['We collect only the information needed to process donations, respond to enquiries, and keep you informed if you choose to hear from us.'],
                    'paragraphs_ar' => ['نجمع فقط المعلومات اللازمة لمعالجة التبرّعات والردّ على الاستفسارات وإبقائك على اطّلاع إن اخترت ذلك.'],
                    'bullets_en' => ['Contact details you provide (name, email, phone)', 'Donation and transaction records', 'Basic, anonymized site-usage analytics'],
                    'bullets_ar' => ['بيانات التواصل التي تقدّمها (الاسم، البريد، الهاتف)', 'سجلّات التبرّع والمعاملات', 'تحليلات استخدام مجهّلة وأساسية للموقع'],
                ],
                [
                    'heading_en' => 'How We Use Information',
                    'heading_ar' => 'كيف نستخدم المعلومات',
                    'paragraphs_en' => ['Information is used to deliver services, issue receipts, share updates you opt into, and improve our programs. We never sell your data.'],
                    'paragraphs_ar' => ['تُستخدم المعلومات لتقديم الخدمات وإصدار الإيصالات ومشاركة التحديثات التي توافق عليها وتحسين برامجنا. ولا نبيع بياناتك أبدًا.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Sharing',
                    'heading_ar' => 'المشاركة',
                    'paragraphs_en' => ['We share data only with trusted service providers (such as payment processors) strictly as needed, and only under confidentiality obligations.'],
                    'paragraphs_ar' => ['نشارك البيانات فقط مع مزوّدي خدمات موثوقين (كمعالجي الدفع) بالقدر اللازم فقط، وتحت التزامات السرّية.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Your Rights',
                    'heading_ar' => 'حقوقك',
                    'paragraphs_en' => ['You may request access to, correction of, or deletion of your personal data, and you can unsubscribe from communications at any time.'],
                    'paragraphs_ar' => ['يمكنك طلب الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها، وإلغاء الاشتراك في المراسلات في أي وقت.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Cookies',
                    'heading_ar' => 'ملفات الارتباط',
                    'paragraphs_en' => ['We use minimal cookies to keep the site working and understand general usage. You can control cookies through your browser settings.'],
                    'paragraphs_ar' => ['نستخدم أقلّ قدرٍ من ملفات الارتباط لإبقاء الموقع يعمل وفهم الاستخدام العام. ويمكنك التحكّم بها عبر إعدادات متصفّحك.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
            ],
        ],
        'terms' => [
            'title_en' => 'Terms of Use',
            'title_ar' => 'شروط الاستخدام',
            'subtitle_en' => 'The terms that govern your use of the GHOSN website and services.',
            'subtitle_ar' => 'الشروط التي تحكم استخدامك لموقع غُصن وخدماته.',
            'updated_en' => 'July 1, 2026',
            'updated_ar' => '١ يوليو ٢٠٢٦',
            'intro_en' => 'By accessing this website you agree to these Terms of Use. Please read them carefully.',
            'intro_ar' => 'بدخولك هذا الموقع فإنك توافق على شروط الاستخدام هذه. يُرجى قراءتها بعناية.',
            'sections' => [
                [
                    'heading_en' => 'Acceptable Use',
                    'heading_ar' => 'الاستخدام المقبول',
                    'paragraphs_en' => ['You agree to use our site lawfully and not to misuse, disrupt, or attempt to gain unauthorized access to any part of it.'],
                    'paragraphs_ar' => ['توافق على استخدام موقعنا بشكل قانوني وعدم إساءة استخدامه أو تعطيله أو محاولة الوصول غير المصرّح به إلى أي جزء منه.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Donations & Payments',
                    'heading_ar' => 'التبرّعات والمدفوعات',
                    'paragraphs_en' => ['All donations are voluntary. By donating you confirm the funds are yours to give and that the information you provide is accurate.'],
                    'paragraphs_ar' => ['جميع التبرّعات طوعية. وبتبرّعك تؤكّد أن الأموال ملكك لتمنحها وأن المعلومات التي تقدّمها دقيقة.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Intellectual Property',
                    'heading_ar' => 'الملكية الفكرية',
                    'paragraphs_en' => ['The GHOSN name, logo, and content are the property of GHOSN Relief Team and may not be used without written permission.'],
                    'paragraphs_ar' => ['اسم غُصن وشعاره ومحتواه ملكٌ لفريق غُصن للإغاثة ولا يجوز استخدامها دون إذنٍ خطّي.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Limitation of Liability',
                    'heading_ar' => 'حدود المسؤولية',
                    'paragraphs_en' => ['The site is provided "as is". GHOSN is not liable for indirect or incidental damages arising from its use, to the extent permitted by law.'],
                    'paragraphs_ar' => ['يُقدَّم الموقع «كما هو». ولا يتحمّل غُصن مسؤولية الأضرار غير المباشرة أو العرضية الناشئة عن استخدامه، بالقدر الذي يسمح به القانون.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Changes to Terms',
                    'heading_ar' => 'تغييرات الشروط',
                    'paragraphs_en' => ['We may update these terms from time to time. Continued use of the site after changes constitutes acceptance of the revised terms.'],
                    'paragraphs_ar' => ['قد نحدّث هذه الشروط من وقتٍ لآخر. واستمرار استخدامك للموقع بعد التغييرات يُعدّ قبولًا للشروط المعدّلة.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
            ],
        ],
        'refund' => [
            'title_en' => 'Refund Policy',
            'title_ar' => 'سياسة الاسترداد',
            'subtitle_en' => 'When and how a donation may be refunded.',
            'subtitle_ar' => 'متى وكيف يمكن استرداد التبرّع.',
            'updated_en' => 'July 1, 2026',
            'updated_ar' => '١ يوليو ٢٠٢٦',
            'intro_en' => 'We are grateful for every gift. We also understand that mistakes happen — this policy explains how refunds are handled.',
            'intro_ar' => 'نحن ممتنّون لكل عطاء. وندرك أيضًا أن الأخطاء تحدث — توضّح هذه السياسة كيف تُعالَج عمليات الاسترداد.',
            'sections' => [
                [
                    'heading_en' => 'Eligibility',
                    'heading_ar' => 'الأهلية',
                    'paragraphs_en' => ['If a donation was made in error or in a duplicate transaction, you may request a refund within 14 days of the gift.'],
                    'paragraphs_ar' => ['إن تمّ التبرّع بالخطأ أو في معاملة مكرّرة، يمكنك طلب الاسترداد خلال ١٤ يومًا من التبرّع.'],
                    'bullets_en' => ['Accidental or duplicate donations', 'Incorrect amount entered in good faith', 'Unauthorized use of a payment method'],
                    'bullets_ar' => ['التبرّعات العَرَضية أو المكرّرة', 'إدخال مبلغ خاطئ بحسن نيّة', 'استخدام غير مصرّح به لوسيلة الدفع'],
                ],
                [
                    'heading_en' => 'How to Request',
                    'heading_ar' => 'كيفية الطلب',
                    'paragraphs_en' => ['Email us with your name, the donation date, and the amount. We will verify the transaction and respond promptly.'],
                    'paragraphs_ar' => ['راسلنا باسمك وتاريخ التبرّع والمبلغ. سنتحقّق من المعاملة ونردّ عليك سريعًا.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Processing Time',
                    'heading_ar' => 'مدة المعالجة',
                    'paragraphs_en' => ['Approved refunds are returned to the original payment method, typically within 5–10 business days depending on your provider.'],
                    'paragraphs_ar' => ['تُعاد المبالغ المعتمَدة إلى وسيلة الدفع الأصلية، عادةً خلال ٥ إلى ١٠ أيام عمل حسب مزوّدك.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
                [
                    'heading_en' => 'Exceptions',
                    'heading_ar' => 'الاستثناءات',
                    'paragraphs_en' => ['Where funds have already been disbursed to a completed program, we will work with you to find a fair resolution.'],
                    'paragraphs_ar' => ['حيثما صُرِفت الأموال بالفعل على برنامجٍ مكتمل، سنعمل معك للوصول إلى حلٍّ عادل.'],
                    'bullets_en' => [],
                    'bullets_ar' => [],
                ],
            ],
        ],
    ],
];
