<?php

$volunteerEmailKeys = [];

foreach (require __DIR__.'/volunteer-emails.php' as $type => $template) {
    $volunteerEmailKeys["volunteers.{$type}_enabled"] = [
        'type' => 'boolean',
        'default' => (bool) ($template['enabled'] ?? true),
    ];

    foreach (['subject', 'heading', 'body'] as $field) {
        $volunteerEmailKeys["volunteers.{$type}_{$field}_en"] = [
            'type' => 'string',
            'default' => (string) ($template["{$field}_en"] ?? ''),
        ];
        $volunteerEmailKeys["volunteers.{$type}_{$field}_ar"] = [
            'type' => 'string',
            'default' => (string) ($template["{$field}_ar"] ?? ''),
        ];
    }
}

return [

    'keys' => array_merge([
        'site.name_en' => ['type' => 'string', 'default' => 'GHOSN Relief Team'],
        'site.name_ar' => ['type' => 'string', 'default' => 'فريق غُصن للإغاثة'],
        'site.slogan_en' => ['type' => 'string', 'default' => 'Giving that grows. Impact that lasts.'],
        'site.slogan_ar' => ['type' => 'string', 'default' => 'عطاءٌ ينمو... وأثرٌ يبقى.'],
        'theme.primary_color' => ['type' => 'string', 'default' => '#0C5A2E'],
        'theme.secondary_color' => ['type' => 'string', 'default' => '#46A45B'],
        'theme.accent_color' => ['type' => 'string', 'default' => '#46A45B'],
        'theme.background_color' => ['type' => 'string', 'default' => '#FAF8F1'],
        'theme.font_en' => ['type' => 'string', 'default' => 'Montserrat'],
        'theme.font_ar' => ['type' => 'string', 'default' => 'Cairo'],
        'site.logo' => ['type' => 'string', 'default' => 'assets/landing/images/logo.webp'],
        'site.logo_media_id' => ['type' => 'integer', 'default' => null],
        'site.favicon' => ['type' => 'string', 'default' => ''],
        'site.favicon_media_id' => ['type' => 'integer', 'default' => null],
        'site.default_language' => ['type' => 'string', 'default' => 'en'],
        'site.enable_animations' => ['type' => 'boolean', 'default' => true],
        'contact.email' => ['type' => 'string', 'default' => 'ghosn.gaza@gmail.com'],
        'contact.inbox_email' => ['type' => 'string', 'default' => ''],
        'contact.phone' => ['type' => 'string', 'default' => ''],
        'contact.address_en' => ['type' => 'string', 'default' => ''],
        'contact.address_ar' => ['type' => 'string', 'default' => ''],
        'contact.office_en' => ['type' => 'string', 'default' => ''],
        'contact.office_ar' => ['type' => 'string', 'default' => ''],
        'contact.page_hero_eyebrow_en' => ['type' => 'string', 'default' => 'We are here to help'],
        'contact.page_hero_eyebrow_ar' => ['type' => 'string', 'default' => 'نحن هنا لمساعدتك'],
        'contact.page_hero_title_en' => ['type' => 'string', 'default' => 'Get in touch with GHOSN'],
        'contact.page_hero_title_ar' => ['type' => 'string', 'default' => 'تواصل مع غُصن'],
        'contact.page_hero_subtitle_en' => ['type' => 'string', 'default' => 'Questions, partnerships, or just a hello — reach out and our team will get back to you shortly.'],
        'contact.page_hero_subtitle_ar' => ['type' => 'string', 'default' => 'أسئلة أو شراكات أو حتى تحية — راسلنا وسيعود إليك فريقنا في أقرب وقت.'],
        'contact.page_info_eyebrow_en' => ['type' => 'string', 'default' => 'Contact details'],
        'contact.page_info_eyebrow_ar' => ['type' => 'string', 'default' => 'بيانات التواصل'],
        'contact.page_info_title_en' => ['type' => 'string', 'default' => 'Reach us directly'],
        'contact.page_info_title_ar' => ['type' => 'string', 'default' => 'تواصل معنا مباشرة'],
        'contact.page_info_body_en' => ['type' => 'string', 'default' => 'Prefer a quick message? Use any channel below, or fill in the form and we will reply as soon as we can.'],
        'contact.page_info_body_ar' => ['type' => 'string', 'default' => 'تفضّل رسالة سريعة؟ استخدم أي وسيلة أدناه، أو املأ النموذج وسنردّ عليك بأسرع ما يمكن.'],
        'navigation.items' => ['type' => 'json', 'default' => null],
        'navigation.donate_label_en' => ['type' => 'string', 'default' => 'Donate Now'],
        'navigation.donate_label_ar' => ['type' => 'string', 'default' => 'تبرّع الآن'],
        'footer.desc_en' => ['type' => 'string', 'default' => 'GHOSN Relief Team brings together donors, volunteers, and partners to deliver lasting humanitarian impact.'],
        'footer.desc_ar' => ['type' => 'string', 'default' => 'يجمع فريق غُصن للإغاثة المتبرعين والمتطوعين والشركاء لتقديم أثر إنساني دائم.'],
        'footer.tagline_en' => ['type' => 'string', 'default' => 'Giving that grows... an impact that lasts'],
        'footer.tagline_ar' => ['type' => 'string', 'default' => 'عطاءٌ ينمو... وأثرٌ يبقى'],
        'footer.quick_title_en' => ['type' => 'string', 'default' => 'Quick links'],
        'footer.quick_title_ar' => ['type' => 'string', 'default' => 'روابط سريعة'],
        'footer.links_title_en' => ['type' => 'string', 'default' => 'Explore'],
        'footer.links_title_ar' => ['type' => 'string', 'default' => 'استكشف'],
        'footer.links' => ['type' => 'json', 'default' => null],
        'footer.contact_title_en' => ['type' => 'string', 'default' => 'Contact'],
        'footer.contact_title_ar' => ['type' => 'string', 'default' => 'تواصل معنا'],
        'footer.follow_title_en' => ['type' => 'string', 'default' => 'Follow us'],
        'footer.follow_title_ar' => ['type' => 'string', 'default' => 'تابعنا'],
        'footer.rights_en' => ['type' => 'string', 'default' => 'All rights reserved.'],
        'footer.rights_ar' => ['type' => 'string', 'default' => 'جميع الحقوق محفوظة.'],
        'social.facebook_url' => ['type' => 'string', 'default' => 'https://facebook.com/ghosnteam'],
        'social.instagram_handle' => ['type' => 'string', 'default' => 'ghosn.team'],
        'donations.enabled' => ['type' => 'boolean', 'default' => true],
        'donations.currency' => ['type' => 'string', 'default' => 'USD'],
        'donations.stripe_enabled' => ['type' => 'boolean', 'default' => false],
        'donations.bank_transfer_enabled' => ['type' => 'boolean', 'default' => true],
        'donations.min_amount' => ['type' => 'integer', 'default' => 5],
        'donations.bank_name_en' => ['type' => 'string', 'default' => ''],
        'donations.bank_name_ar' => ['type' => 'string', 'default' => ''],
        'donations.account_holder_en' => ['type' => 'string', 'default' => 'GHOSN Relief Team'],
        'donations.account_holder_ar' => ['type' => 'string', 'default' => 'فريق غُصن للإغاثة'],
        'donations.iban' => ['type' => 'string', 'default' => ''],
        'donations.account_number' => ['type' => 'string', 'default' => ''],
        'donations.swift' => ['type' => 'string', 'default' => ''],
        'donations.instructions_en' => ['type' => 'string', 'default' => 'Please include your donation reference in the transfer description.'],
        'donations.instructions_ar' => ['type' => 'string', 'default' => 'يرجى ذكر رقم مرجع الدفع في وصف التحويل.'],
        'payments.currency' => ['type' => 'string', 'default' => 'USD'],
        'payments.min_amount' => ['type' => 'integer', 'default' => 5],
        'payments.max_amount' => ['type' => 'integer', 'default' => 50000],
        'payments.receipt_email' => ['type' => 'string', 'default' => ''],
        'payments.stripe_enabled' => ['type' => 'boolean', 'default' => false],
        'payments.stripe_product_name' => ['type' => 'string', 'default' => 'GHOSN Relief Support Contribution'],
        'payments.stripe_product_description' => ['type' => 'string', 'default' => 'Community support payment for GHOSN Relief Team activities.'],
        'payments.paypal_enabled' => ['type' => 'boolean', 'default' => false],
        'payments.paypal_mode' => ['type' => 'string', 'default' => 'sandbox'],
        'payments.paypal_item_name' => ['type' => 'string', 'default' => 'GHOSN Relief Support Contribution'],
        'payments.paypal_item_description' => ['type' => 'string', 'default' => 'Community support payment for GHOSN Relief Team activities.'],
        'email.from_name' => ['type' => 'string', 'default' => 'GHOSN Relief Team'],
        'email.from_email' => ['type' => 'string', 'default' => ''],
        'email.admin_notification_email' => ['type' => 'string', 'default' => ''],
        'email.donor_receipts_enabled' => ['type' => 'boolean', 'default' => true],
        'email.admin_alerts_enabled' => ['type' => 'boolean', 'default' => true],
        'email.footer_en' => ['type' => 'string', 'default' => 'Thank you for supporting GHOSN Relief Team.'],
        'email.footer_ar' => ['type' => 'string', 'default' => 'شكراً لدعمكم فريق غُصن للإغاثة.'],
        'newsletter.enabled' => ['type' => 'boolean', 'default' => true],
        'newsletter.title_en' => ['type' => 'string', 'default' => 'Stay close to the impact'],
        'newsletter.title_ar' => ['type' => 'string', 'default' => 'ابقَ قريبًا من الأثر'],
        'newsletter.subtitle_en' => ['type' => 'string', 'default' => 'Join our newsletter for stories, campaign milestones, and ways to help.'],
        'newsletter.subtitle_ar' => ['type' => 'string', 'default' => 'اشترك في نشرتنا للقصص ومحطات الحملات وطرق المساعدة.'],
        'newsletter.placeholder_en' => ['type' => 'string', 'default' => 'Your email address'],
        'newsletter.placeholder_ar' => ['type' => 'string', 'default' => 'بريدك الإلكتروني'],
        'newsletter.button_en' => ['type' => 'string', 'default' => 'Subscribe'],
        'newsletter.button_ar' => ['type' => 'string', 'default' => 'اشترك'],
        'newsletter.success_en' => ['type' => 'string', 'default' => 'You are subscribed — thank you!'],
        'newsletter.success_ar' => ['type' => 'string', 'default' => 'تم اشتراكك — شكرًا لك!'],
        'legal.pages' => ['type' => 'json', 'default' => null],
        'team.page' => ['type' => 'json', 'default' => null],
        'about.page' => ['type' => 'json', 'default' => null],
        'contact.page' => ['type' => 'json', 'default' => null],
        'maintenance.enabled' => ['type' => 'boolean', 'default' => false],
        'maintenance.eyebrow_en' => ['type' => 'string', 'default' => 'Scheduled maintenance'],
        'maintenance.eyebrow_ar' => ['type' => 'string', 'default' => 'صيانة مؤقتة'],
        'maintenance.title_en' => ['type' => 'string', 'default' => 'We\'ll be back soon'],
        'maintenance.title_ar' => ['type' => 'string', 'default' => 'سنعود قريباً'],
        'maintenance.message_en' => ['type' => 'string', 'default' => 'We\'re making a few updates behind the scenes. Thank you for your patience — we\'ll be back shortly.'],
        'maintenance.message_ar' => ['type' => 'string', 'default' => 'نقوم حالياً بتحديثات على الموقع. شكراً لصبركم — سنعود قريباً.'],
        'seo.title_en' => ['type' => 'string', 'default' => ''],
        'seo.title_ar' => ['type' => 'string', 'default' => ''],
        'seo.description_en' => ['type' => 'string', 'default' => 'GHOSN Relief Team brings together donors, volunteers, and partners to deliver lasting humanitarian impact.'],
        'seo.description_ar' => ['type' => 'string', 'default' => 'يجمع فريق غُصن للإغاثة المتبرعين والمتطوعين والشركاء لتقديم أثر إنساني دائم.'],
        'seo.image' => ['type' => 'string', 'default' => ''],
        'seo.image_media_id' => ['type' => 'integer', 'default' => null],
        'seo.robots_default' => ['type' => 'string', 'default' => 'index,follow'],
        'seo.canonical_mode' => ['type' => 'string', 'default' => 'current'],
        'seo.twitter_site' => ['type' => 'string', 'default' => ''],
        'seo.organization_type' => ['type' => 'string', 'default' => 'NGO'],
        'seo.organization_name_en' => ['type' => 'string', 'default' => ''],
        'seo.organization_name_ar' => ['type' => 'string', 'default' => ''],
        'seo.schema_organization' => ['type' => 'boolean', 'default' => true],
        'seo.schema_website' => ['type' => 'boolean', 'default' => true],
        'seo.schema_article' => ['type' => 'boolean', 'default' => true],
        'seo.schema_breadcrumb' => ['type' => 'boolean', 'default' => true],
        'seo.schema_faq' => ['type' => 'boolean', 'default' => true],
        'seo.robots_txt' => ['type' => 'json', 'default' => null],
        'seo.sitemap_enabled' => ['type' => 'boolean', 'default' => true],
        'seo.sitemap_include_pages' => ['type' => 'boolean', 'default' => true],
        'seo.sitemap_include_posts' => ['type' => 'boolean', 'default' => true],
        'seo.sitemap_include_campaigns' => ['type' => 'boolean', 'default' => true],
        'seo.sitemap_include_categories' => ['type' => 'boolean', 'default' => true],
        'seo.sitemap_changefreq' => ['type' => 'string', 'default' => 'weekly'],

        'google.analytics.enabled' => ['type' => 'boolean', 'default' => false],
        'google.analytics.measurement_id' => ['type' => 'string', 'default' => ''],
        'google.analytics.anonymize_ip' => ['type' => 'boolean', 'default' => true],
        'google.analytics.debug' => ['type' => 'boolean', 'default' => false],
        'google.analytics.enhanced_measurement' => ['type' => 'boolean', 'default' => true],
        'google.analytics.ecommerce' => ['type' => 'boolean', 'default' => false],
        'google.gtm.enabled' => ['type' => 'boolean', 'default' => false],
        'google.gtm.container_id' => ['type' => 'string', 'default' => ''],
        'google.gtm.inject_head' => ['type' => 'boolean', 'default' => true],
        'google.gtm.inject_body' => ['type' => 'boolean', 'default' => true],
        'google.search_console.meta_tag' => ['type' => 'string', 'default' => ''],
        'google.search_console.verification_file' => ['type' => 'string', 'default' => ''],
        'google.consent.enabled' => ['type' => 'boolean', 'default' => true],
        'google.consent.analytics_storage' => ['type' => 'string', 'default' => 'denied'],
        'google.consent.ad_storage' => ['type' => 'string', 'default' => 'denied'],
        'google.consent.ad_user_data' => ['type' => 'string', 'default' => 'denied'],
        'google.consent.ad_personalization' => ['type' => 'string', 'default' => 'denied'],
        'google.consent.wait_for_update' => ['type' => 'integer', 'default' => 500],
        'google.consent.regions' => ['type' => 'string', 'default' => ''],
        'google.consent.cookie_days' => ['type' => 'integer', 'default' => 365],
        'google.adsense.enabled' => ['type' => 'boolean', 'default' => false],
        'google.adsense.publisher_id' => ['type' => 'string', 'default' => ''],
        'google.adsense.auto_ads' => ['type' => 'boolean', 'default' => true],
        'google.maps.enabled' => ['type' => 'boolean', 'default' => false],
        'google.maps.api_key' => ['type' => 'string', 'default' => ''],
        'google.maps.language' => ['type' => 'string', 'default' => ''],
        'google.maps.region' => ['type' => 'string', 'default' => ''],
        'google.recaptcha.enabled' => ['type' => 'boolean', 'default' => false],
        'google.recaptcha.site_key' => ['type' => 'string', 'default' => ''],
        'google.recaptcha.secret_key' => ['type' => 'string', 'default' => ''],
        'google.recaptcha.score_threshold' => ['type' => 'string', 'default' => '0.5'],
        'google.recaptcha.contact' => ['type' => 'boolean', 'default' => true],
        'google.recaptcha.login' => ['type' => 'boolean', 'default' => false],
        'google.recaptcha.register' => ['type' => 'boolean', 'default' => false],
        'google.merchant.meta_tag' => ['type' => 'string', 'default' => ''],
        'google.fonts.enable_cdn' => ['type' => 'boolean', 'default' => false],
        'google.fonts.preconnect' => ['type' => 'boolean', 'default' => true],
        'google.fonts.display_swap' => ['type' => 'boolean', 'default' => true],
        'google.fonts.prefer_local' => ['type' => 'boolean', 'default' => true],
        'google.fonts.family_en' => ['type' => 'string', 'default' => 'Montserrat'],
        'google.fonts.family_ar' => ['type' => 'string', 'default' => 'Cairo'],
    ], $volunteerEmailKeys),

    'groups' => [
        'general' => [
            'keys' => [
                'site.name_en',
                'site.name_ar',
                'site.slogan_en',
                'site.slogan_ar',
                'site.default_language',
                'site.enable_animations',
            ],
        ],
        'branding' => [
            'keys' => [
                'site.logo_media_id',
                'site.favicon_media_id',
            ],
            'files' => ['site.logo', 'site.favicon'],
        ],
        'typography' => [
            'keys' => [
                'theme.font_en',
                'theme.font_ar',
            ],
        ],
        'colors' => [
            'keys' => [
                'theme.primary_color',
                'theme.secondary_color',
                'theme.accent_color',
                'theme.background_color',
            ],
        ],
        'social' => [
            'keys' => [
                'social.facebook_url',
                'social.instagram_handle',
            ],
        ],
        'contact' => [
            'keys' => [
                'contact.email',
                'contact.inbox_email',
                'contact.phone',
                'contact.address_en',
                'contact.address_ar',
                'contact.office_en',
                'contact.office_ar',
                'contact.page_hero_eyebrow_en',
                'contact.page_hero_eyebrow_ar',
                'contact.page_hero_title_en',
                'contact.page_hero_title_ar',
                'contact.page_hero_subtitle_en',
                'contact.page_hero_subtitle_ar',
                'contact.page_info_eyebrow_en',
                'contact.page_info_eyebrow_ar',
                'contact.page_info_title_en',
                'contact.page_info_title_ar',
                'contact.page_info_body_en',
                'contact.page_info_body_ar',
                'contact.page',
            ],
        ],
        'navigation' => [
            'keys' => [
                'navigation.items',
                'navigation.donate_label_en',
                'navigation.donate_label_ar',
            ],
        ],
        'footer' => [
            'keys' => [
                'footer.desc_en',
                'footer.desc_ar',
                'footer.tagline_en',
                'footer.tagline_ar',
                'footer.quick_title_en',
                'footer.quick_title_ar',
                'footer.links_title_en',
                'footer.links_title_ar',
                'footer.links',
                'footer.contact_title_en',
                'footer.contact_title_ar',
                'footer.follow_title_en',
                'footer.follow_title_ar',
                'footer.rights_en',
                'footer.rights_ar',
            ],
        ],
        'donations' => [
            'keys' => [
                'donations.enabled',
                'donations.bank_transfer_enabled',
                'donations.bank_name_en',
                'donations.bank_name_ar',
                'donations.account_holder_en',
                'donations.account_holder_ar',
                'donations.iban',
                'donations.account_number',
                'donations.swift',
                'donations.instructions_en',
                'donations.instructions_ar',
            ],
        ],
        'payments' => [
            'keys' => [
                'payments.currency',
                'payments.min_amount',
                'payments.max_amount',
                'payments.receipt_email',
                'payments.stripe_enabled',
                'payments.stripe_product_name',
                'payments.stripe_product_description',
                'payments.paypal_enabled',
                'payments.paypal_mode',
                'payments.paypal_item_name',
                'payments.paypal_item_description',
            ],
        ],
        'email' => [
            'keys' => [
                'email.from_name',
                'email.from_email',
                'email.admin_notification_email',
                'email.donor_receipts_enabled',
                'email.admin_alerts_enabled',
                'email.footer_en',
                'email.footer_ar',
            ],
        ],
        'advanced' => [
            'keys' => [],
        ],
        'homepage' => [
            'keys' => [],
        ],
        'newsletter' => [
            'keys' => [
                'newsletter.enabled',
                'newsletter.title_en',
                'newsletter.title_ar',
                'newsletter.subtitle_en',
                'newsletter.subtitle_ar',
                'newsletter.placeholder_en',
                'newsletter.placeholder_ar',
                'newsletter.button_en',
                'newsletter.button_ar',
                'newsletter.success_en',
                'newsletter.success_ar',
            ],
        ],
        'volunteers' => [
            'keys' => array_keys($volunteerEmailKeys),
        ],
        'legal' => [
            'keys' => ['legal.pages'],
        ],
        'team' => [
            'keys' => ['team.page'],
        ],
        'about' => [
            'keys' => ['about.page'],
        ],
        'maintenance' => [
            'keys' => [
                'maintenance.enabled',
                'maintenance.eyebrow_en',
                'maintenance.eyebrow_ar',
                'maintenance.title_en',
                'maintenance.title_ar',
                'maintenance.message_en',
                'maintenance.message_ar',
            ],
        ],
        'seo' => [
            'keys' => [
                'seo.title_en',
                'seo.title_ar',
                'seo.description_en',
                'seo.description_ar',
                'seo.image_media_id',
                'seo.robots_default',
                'seo.canonical_mode',
                'seo.twitter_site',
                'seo.organization_type',
                'seo.organization_name_en',
                'seo.organization_name_ar',
                'seo.schema_organization',
                'seo.schema_website',
                'seo.schema_article',
                'seo.schema_breadcrumb',
                'seo.schema_faq',
                'seo.robots_txt',
                'seo.sitemap_enabled',
                'seo.sitemap_include_pages',
                'seo.sitemap_include_posts',
                'seo.sitemap_include_campaigns',
                'seo.sitemap_include_categories',
                'seo.sitemap_changefreq',
            ],
            'files' => ['seo.image'],
        ],
        'google' => [
            'keys' => [
                'google.analytics.enabled',
                'google.analytics.measurement_id',
                'google.analytics.anonymize_ip',
                'google.analytics.debug',
                'google.analytics.enhanced_measurement',
                'google.analytics.ecommerce',
                'google.gtm.enabled',
                'google.gtm.container_id',
                'google.gtm.inject_head',
                'google.gtm.inject_body',
                'google.search_console.meta_tag',
                'google.search_console.verification_file',
                'google.consent.enabled',
                'google.consent.analytics_storage',
                'google.consent.ad_storage',
                'google.consent.ad_user_data',
                'google.consent.ad_personalization',
                'google.consent.wait_for_update',
                'google.consent.regions',
                'google.consent.cookie_days',
                'google.adsense.enabled',
                'google.adsense.publisher_id',
                'google.adsense.auto_ads',
                'google.maps.enabled',
                'google.maps.api_key',
                'google.maps.language',
                'google.maps.region',
                'google.recaptcha.enabled',
                'google.recaptcha.site_key',
                'google.recaptcha.secret_key',
                'google.recaptcha.score_threshold',
                'google.recaptcha.contact',
                'google.recaptcha.login',
                'google.recaptcha.register',
                'google.merchant.meta_tag',
                'google.fonts.enable_cdn',
                'google.fonts.preconnect',
                'google.fonts.display_swap',
                'google.fonts.prefer_local',
                'google.fonts.family_en',
                'google.fonts.family_ar',
            ],
            'files' => ['google.search_console.verification_upload'],
        ],
    ],

    'hub_order' => [
        'general',
        'maintenance',
        'seo',
        'google',
        'branding',
        'colors',
        'typography',
        'homepage',
        'navigation',
        'footer',
        'newsletter',
        'contact',
        'social',
        'donations',
        'payments',
        'email',
        'volunteers',
        'legal',
        'team',
        'about',
        'advanced',
    ],

    'hub_cards' => [
        'general' => ['icon' => 'general', 'editable' => true],
        'maintenance' => ['icon' => 'general', 'editable' => true],
        'seo' => ['icon' => 'general', 'editable' => true],
        'google' => ['icon' => 'google', 'editable' => true],
        'branding' => ['icon' => 'branding', 'editable' => true],
        'colors' => ['icon' => 'colors', 'editable' => true],
        'typography' => ['icon' => 'typography', 'editable' => true],
        'homepage' => ['icon' => 'homepage', 'editable' => false],
        'navigation' => ['icon' => 'homepage', 'editable' => true],
        'footer' => ['icon' => 'homepage', 'editable' => true],
        'newsletter' => ['icon' => 'newsletter', 'editable' => true],
        'contact' => ['icon' => 'contact', 'editable' => true],
        'social' => ['icon' => 'social', 'editable' => true],
        'donations' => ['icon' => 'donations', 'editable' => true],
        'payments' => ['icon' => 'payments', 'editable' => true],
        'email' => ['icon' => 'contact', 'editable' => true],
        'volunteers' => ['icon' => 'contact', 'editable' => true],
        'legal' => ['icon' => 'homepage', 'editable' => true],
        'team' => ['icon' => 'homepage', 'editable' => true],
        'about' => ['icon' => 'homepage', 'editable' => true],
        'advanced' => ['icon' => 'advanced', 'editable' => false],
    ],

    'allowed_groups' => [
        'general',
        'maintenance',
        'seo',
        'google',
        'branding',
        'typography',
        'colors',
        'social',
        'contact',
        'donations',
        'payments',
        'email',
        'volunteers',
        'homepage',
        'navigation',
        'footer',
        'newsletter',
        'legal',
        'team',
        'about',
        'advanced',
    ],

];
