<?php

return [
    'sections' => [
        'hero' => true,
        'stats' => true,
        'leadership' => true,
        'departments' => true,
        'culture' => true,
        'cta' => true,
    ],
    'hero' => [
        'eyebrow_en' => 'The people behind GHOSN',
        'eyebrow_ar' => 'الأشخاص خلف غُصن',
        'title_en' => 'Meet the team growing hope',
        'title_ar' => 'تعرّف على الفريق الذي يُنمّي الأمل',
        'subtitle_en' => 'A dedicated group of staff and volunteers who turn everyday generosity into action — every single day.',
        'subtitle_ar' => 'مجموعة متفانية من الموظفين والمتطوعين تحوّل العطاء اليومي إلى فعلٍ ملموس — كل يوم.',
    ],
    'stats' => [
        ['end' => 1450, 'suffix' => '+', 'label_en' => 'Volunteers', 'label_ar' => 'متطوّع'],
        ['end' => 42, 'suffix' => '', 'label_en' => 'Core staff', 'label_ar' => 'موظف أساسي'],
        ['end' => 60, 'suffix' => '+', 'label_en' => 'Communities served', 'label_ar' => 'مجتمعًا خدمناه'],
        ['end' => 8, 'suffix' => '', 'label_en' => 'Years together', 'label_ar' => 'سنوات معًا'],
    ],
    'leadership' => [
        'eyebrow_en' => 'Leadership',
        'eyebrow_ar' => 'القيادة',
        'title_en' => 'Guided by experience and heart',
        'title_ar' => 'بخبرةٍ وقلب',
        'intro_en' => 'The people who steer GHOSN\'s mission and keep dignity at the center of everything we do.',
        'intro_ar' => 'الأشخاص الذين يقودون رسالة غُصن ويبقون الكرامة في قلب كل ما نقوم به.',
    ],
    'leaders' => [
        [
            'name_en' => 'Yusuf Al-Rashid',
            'name_ar' => 'يوسف الرشيد',
            'role_en' => 'Founder & Director',
            'role_ar' => 'المؤسّس والمدير',
            'bio_en' => 'Founded GHOSN in 2018 with a single food-basket drive. Leads strategy and partnerships across all programs.',
            'bio_ar' => 'أسّس غُصن عام ٢٠١٨ بحملة سلال غذاء واحدة. يقود الاستراتيجية والشراكات في جميع البرامج.',
            'image_media_id' => null,
            'linkedin_url' => '',
            'x_url' => '',
            'email' => '',
        ],
        [
            'name_en' => 'Layla Haddad',
            'name_ar' => 'ليلى حدّاد',
            'role_en' => 'Programs Lead',
            'role_ar' => 'مسؤولة البرامج',
            'bio_en' => 'Designs and oversees our relief programs, from clean water to education, always in step with communities.',
            'bio_ar' => 'تصمّم برامج الإغاثة وتشرف عليها، من المياه النظيفة إلى التعليم، دائمًا بالتناغم مع المجتمعات.',
            'image_media_id' => null,
            'linkedin_url' => '',
            'x_url' => '',
            'email' => '',
        ],
        [
            'name_en' => 'Omar Khalil',
            'name_ar' => 'عمر خليل',
            'role_en' => 'Field Operations',
            'role_ar' => 'العمليات الميدانية',
            'bio_en' => 'Coordinates logistics and on-the-ground delivery so aid reaches families quickly and with dignity.',
            'bio_ar' => 'ينسّق اللوجستيات والتسليم الميداني لتصل المساعدات إلى الأسر بسرعةٍ وكرامة.',
            'image_media_id' => null,
            'linkedin_url' => '',
            'x_url' => '',
            'email' => '',
        ],
        [
            'name_en' => 'Sara Mansour',
            'name_ar' => 'سارة منصور',
            'role_en' => 'Community & Outreach',
            'role_ar' => 'المجتمع والتواصل',
            'bio_en' => 'Builds the volunteer network and keeps donors close to the impact their giving creates.',
            'bio_ar' => 'تبني شبكة المتطوعين وتُبقي المتبرّعين قريبين من الأثر الذي يصنعه عطاؤهم.',
            'image_media_id' => null,
            'linkedin_url' => '',
            'x_url' => '',
            'email' => '',
        ],
    ],
    'departments' => [
        'eyebrow_en' => 'Our departments',
        'eyebrow_ar' => 'أقسامنا',
        'title_en' => 'How the team is organized',
        'title_ar' => 'كيف يتنظّم الفريق',
        'members_label_en' => 'members',
        'members_label_ar' => 'عضوًا',
        'items' => [
            [
                'key' => 'field',
                'count' => 24,
                'name_en' => 'Field Relief',
                'name_ar' => 'الإغاثة الميدانية',
                'desc_en' => 'Delivers aid on the ground — water, food, shelter and emergency response.',
                'desc_ar' => 'توصل المساعدات ميدانيًا — ماء وغذاء ومأوى واستجابة طارئة.',
            ],
            [
                'key' => 'fund',
                'count' => 9,
                'name_en' => 'Fundraising',
                'name_ar' => 'جمع التبرّعات',
                'desc_en' => 'Grows the giving that fuels every campaign, with full transparency.',
                'desc_ar' => 'ينمّي العطاء الذي يغذّي كل حملة، بشفافية كاملة.',
            ],
            [
                'key' => 'media',
                'count' => 6,
                'name_en' => 'Media & Outreach',
                'name_ar' => 'الإعلام والتواصل',
                'desc_en' => 'Tells the stories, runs the campaigns, and keeps communities connected.',
                'desc_ar' => 'يروي القصص ويدير الحملات ويُبقي المجتمعات على تواصل.',
            ],
            [
                'key' => 'edu',
                'count' => 12,
                'name_en' => 'Education & Youth',
                'name_ar' => 'التعليم والشباب',
                'desc_en' => 'Runs school meals, tuition support and vocational training programs.',
                'desc_ar' => 'يدير الوجبات المدرسية ودعم الرسوم وبرامج التدريب المهني.',
            ],
        ],
    ],
    'culture' => [
        'eyebrow_en' => 'Our culture',
        'eyebrow_ar' => 'ثقافتنا',
        'title_en' => 'A team that walks alongside',
        'title_ar' => 'فريقٌ يسير إلى جانبك',
        'body_en' => 'We are volunteers, organizers and neighbors first. What unites us is a belief that relief works best when it is close, respectful, and built to last.',
        'body_ar' => 'نحن متطوعون ومنظّمون وجيران قبل كل شيء. يوحّدنا إيمانٌ بأن الإغاثة تنجح حين تكون قريبةً ومحترمةً وباقية.',
        'image_media_id' => null,
        'points' => [
            ['title_en' => 'Community-led', 'title_ar' => 'يقوده المجتمع', 'body_en' => 'Local voices guide every decision we make.', 'body_ar' => 'الأصوات المحلية توجّه كل قرار نتخذه.'],
            ['title_en' => 'Learning together', 'title_ar' => 'نتعلّم معًا', 'body_en' => 'Training and mentorship at every level.', 'body_ar' => 'تدريب وإرشاد على كل المستويات.'],
            ['title_en' => 'Dignity first', 'title_ar' => 'الكرامة أولًا', 'body_en' => 'We serve people, never headlines.', 'body_ar' => 'نخدم الناس، لا العناوين.'],
            ['title_en' => 'Built to last', 'title_ar' => 'بُني ليدوم', 'body_en' => 'We measure success in lasting change.', 'body_ar' => 'نقيس النجاح بالتغيير الدائم.'],
        ],
    ],
    'cta' => [
        'title_en' => 'There is a place for you on this team',
        'title_ar' => 'هناك مكانٌ لك في هذا الفريق',
        'subtitle_en' => 'Whether you have an hour a week or a whole skillset to share — your hands can help hope grow.',
        'subtitle_ar' => 'سواءً لديك ساعةٌ في الأسبوع أو مهاراتٌ كاملة تشاركها — يداك تساعدان الأمل على النمو.',
        'primary_en' => 'Become a volunteer',
        'primary_ar' => 'كن متطوعًا',
        'primary_url' => '/volunteer',
        'secondary_en' => 'Get in touch',
        'secondary_ar' => 'تواصل معنا',
        'secondary_url' => '/contact',
    ],
];
