<?php

/**
 * Volunteer page defaults — aligned with GHOSN Relief Team Landing Page/Volunteer.dc.html
 */
return [
    'defaults' => [
        'hero_eyebrow_en' => 'Become a volunteer',
        'hero_eyebrow_ar' => 'كن متطوعًا',
        'hero_title_en' => 'Lend your hands. Grow lasting hope.',
        'hero_title_ar' => 'امنح يديك. وازرع أملًا يبقى.',
        'hero_subtitle_en' => 'Join a community that shows up when it matters most. Whatever your skills or schedule, there is a place for you at GHOSN.',
        'hero_subtitle_ar' => 'انضم إلى مجتمعٍ يحضر عند الحاجة. مهما كانت مهاراتك أو وقتك، هناك مكانٌ لك في غُصن.',
        'hero_cta_en' => 'Apply to volunteer',
        'hero_cta_ar' => 'قدّم للتطوّع',
        'hero_image_media_id' => null,

        'why_eyebrow_en' => 'Why volunteer',
        'why_eyebrow_ar' => 'لماذا تتطوّع',
        'why_title_en' => 'More than help — a shared purpose',
        'why_title_ar' => 'أكثر من مساعدة — هدفٌ مشترك',
        'why_intro_en' => 'Volunteering with GHOSN is a chance to turn compassion into real, visible change.',
        'why_intro_ar' => 'التطوّع مع غُصن فرصةٌ لتحويل الرحمة إلى تغييرٍ حقيقيٍّ ملموس.',

        'benefits' => [
            ['key' => 'impact', 'title_en' => 'Real, visible impact', 'title_ar' => 'أثرٌ ملموس وواضح', 'body_en' => 'See exactly how your time turns into clean water, meals, and hope for families.', 'body_ar' => 'ترى بنفسك كيف يتحوّل وقتك إلى ماءٍ نظيف ووجباتٍ وأملٍ للأسر.'],
            ['key' => 'grow', 'title_en' => 'Grow your skills', 'title_ar' => 'طوّر مهاراتك', 'body_en' => 'Training, mentorship, and hands-on experience across every kind of relief work.', 'body_ar' => 'تدريب وإرشاد وخبرة عملية في كل أنواع العمل الإغاثي.'],
            ['key' => 'community', 'title_en' => 'A warm community', 'title_ar' => 'مجتمعٌ دافئ', 'body_en' => 'Join a network of people who care deeply and support one another.', 'body_ar' => 'انضم إلى شبكةٍ من الناس يهتمّون بعمقٍ ويدعم بعضهم بعضًا.'],
        ],

        'areas_eyebrow_en' => 'Where you can help',
        'areas_eyebrow_ar' => 'أين يمكنك المساعدة',
        'areas_title_en' => 'Volunteering areas',
        'areas_title_ar' => 'مجالات التطوّع',

        'area_items' => [
            ['key' => 'field', 'title_en' => 'Field Relief', 'title_ar' => 'الإغاثة الميدانية', 'body_en' => 'Distribute aid and support families directly on the ground.', 'body_ar' => 'وزّع المساعدات وادعم الأسر مباشرةً في الميدان.'],
            ['key' => 'fund', 'title_en' => 'Fundraising', 'title_ar' => 'جمع التبرّعات', 'body_en' => 'Help organize campaigns and grow the giving that fuels our work.', 'body_ar' => 'ساعد في تنظيم الحملات وتنمية العطاء الذي يغذّي عملنا.'],
            ['key' => 'media', 'title_en' => 'Media & Outreach', 'title_ar' => 'الإعلام والتواصل', 'body_en' => 'Tell stories, manage social media, and spread the word.', 'body_ar' => 'اروِ القصص وأدر وسائل التواصل وانشر الرسالة.'],
            ['key' => 'logistics', 'title_en' => 'Logistics', 'title_ar' => 'اللوجستيات', 'body_en' => 'Coordinate supplies, transport, and behind-the-scenes operations.', 'body_ar' => 'نسّق الإمدادات والنقل والعمليات خلف الكواليس.'],
            ['key' => 'edu', 'title_en' => 'Education & Youth', 'title_ar' => 'التعليم والشباب', 'body_en' => 'Mentor youth and support school and training programs.', 'body_ar' => 'أرشد الشباب وادعم برامج المدارس والتدريب.'],
        ],

        'how_eyebrow_en' => 'How it works',
        'how_eyebrow_ar' => 'كيف يعمل',
        'how_title_en' => 'From application to impact in four steps',
        'how_title_ar' => 'من التقديم إلى الأثر في أربع خطوات',

        'steps' => [
            ['title_en' => 'Apply', 'title_ar' => 'قدّم', 'body_en' => 'Fill in the short form below — it takes just a few minutes.', 'body_ar' => 'املأ النموذج القصير أدناه — لا يستغرق سوى دقائق.'],
            ['title_en' => 'Chat', 'title_ar' => 'تحدّث', 'body_en' => 'We reach out for a friendly conversation about your interests.', 'body_ar' => 'نتواصل معك لمحادثةٍ ودّية حول اهتماماتك.'],
            ['title_en' => 'Onboard', 'title_ar' => 'انضمّ', 'body_en' => 'Get a short orientation and meet your team.', 'body_ar' => 'احصل على توجيهٍ قصير وتعرّف على فريقك.'],
            ['title_en' => 'Start giving', 'title_ar' => 'ابدأ العطاء', 'body_en' => 'Join a program and begin making a real difference.', 'body_ar' => 'انضم إلى برنامج وابدأ في إحداث فرقٍ حقيقي.'],
        ],

        'testimonial_quote_en' => 'I came to give a few weekends. Two years later, GHOSN feels like family — and I have seen with my own eyes how much a small hand can change.',
        'testimonial_quote_ar' => 'جئت لأتطوّع بضع عطلات. وبعد عامين، صار غُصن كالعائلة — ورأيت بعينيّ كم يمكن ليدٍ صغيرة أن تغيّر.',
        'testimonial_name_en' => 'Layla H.',
        'testimonial_name_ar' => 'ليلى ح.',
        'testimonial_role_en' => 'Field volunteer since 2024',
        'testimonial_role_ar' => 'متطوّعة ميدانية منذ ٢٠٢٤',
        'testimonial_initial_en' => 'L',
        'testimonial_initial_ar' => 'ل',

        'apply_eyebrow_en' => 'Join us',
        'apply_eyebrow_ar' => 'انضم إلينا',
        'apply_title_en' => 'Volunteer application',
        'apply_title_ar' => 'نموذج التطوّع',
        'apply_intro_en' => 'Tell us a little about yourself and how you would like to help.',
        'apply_intro_ar' => 'أخبرنا قليلًا عن نفسك وكيف تودّ المساعدة.',

        'name_label_en' => 'Full name',
        'name_label_ar' => 'الاسم الكامل',
        'name_placeholder_en' => 'Your full name',
        'name_placeholder_ar' => 'اسمك الكامل',
        'age_label_en' => 'Age',
        'age_label_ar' => 'العمر',
        'age_placeholder_en' => 'Your age',
        'age_placeholder_ar' => 'عمرك',
        'phone_label_en' => 'Phone number',
        'phone_label_ar' => 'رقم الهاتف',
        'phone_placeholder_en' => '+1 (555) 000-0000',
        'phone_placeholder_ar' => '+٩٦٦ ٥٠ ٠٠٠ ٠٠٠٠',
        'email_label_en' => 'Email',
        'email_label_ar' => 'البريد الإلكتروني',
        'email_placeholder_en' => 'you@email.com',
        'email_placeholder_ar' => 'you@email.com',
        'area_label_en' => 'Preferred area',
        'area_label_ar' => 'المجال المفضّل',
        'area_placeholder_en' => 'Choose an area',
        'area_placeholder_ar' => 'اختر مجالًا',
        'availability_label_en' => 'Availability',
        'availability_label_ar' => 'التوفّر',
        'avail_weekdays_en' => 'Weekdays',
        'avail_weekdays_ar' => 'أيام الأسبوع',
        'avail_weekends_en' => 'Weekends',
        'avail_weekends_ar' => 'عطلة الأسبوع',
        'avail_remote_en' => 'Remote',
        'avail_remote_ar' => 'عن بُعد',
        'message_label_en' => 'Why do you want to volunteer?',
        'message_label_ar' => 'لماذا تريد التطوّع؟',
        'message_placeholder_en' => 'Tell us what motivates you (optional)',
        'message_placeholder_ar' => 'أخبرنا بما يحفّزك (اختياري)',
        'agree_label_en' => 'I agree to be contacted by GHOSN about volunteering opportunities.',
        'agree_label_ar' => 'أوافق على أن يتواصل معي غُصن بخصوص فرص التطوّع.',
        'submit_en' => 'Submit application',
        'submit_ar' => 'أرسل الطلب',
        'sending_en' => 'Sending…',
        'sending_ar' => 'جارٍ الإرسال…',
        'error_en' => 'Something went wrong. Please try again.',
        'error_ar' => 'حدث خطأ ما. حاول مرة أخرى.',

        'thanks_title_en' => 'Welcome to the team!',
        'thanks_title_ar' => 'أهلًا بك في الفريق!',
        'thanks_body_en' => 'Thank you for stepping up. Our volunteer coordinator will reach out to you very soon.',
        'thanks_body_ar' => 'شكرًا لتقدّمك. سيتواصل معك منسّق المتطوعين قريبًا جدًا.',
        'thanks_home_en' => 'Back to home',
        'thanks_home_ar' => 'العودة للرئيسية',
        'thanks_explore_en' => 'Explore campaigns',
        'thanks_explore_ar' => 'استكشف الحملات',

        'form_areas' => [
            ['value' => 'field_relief', 'label_en' => 'Field relief', 'label_ar' => 'الإغاثة الميدانية'],
            ['value' => 'fundraising', 'label_en' => 'Fundraising', 'label_ar' => 'جمع التبرعات'],
            ['value' => 'media', 'label_en' => 'Media and outreach', 'label_ar' => 'الإعلام والتواصل'],
            ['value' => 'logistics', 'label_en' => 'Logistics', 'label_ar' => 'اللوجستيات'],
            ['value' => 'education', 'label_en' => 'Education and youth', 'label_ar' => 'التعليم والشباب'],
        ],
    ],
];
